platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 2.4.1

inputs:
- name: perilous_wilds

outputs:
- name: workspace

run:
  path: ./perilous_wilds/ci/test.sh
